version: '3.9'
services:
  shuffle-shop:
    image: anssi/fcsc2020-web-shuffle-shop:latest
    ports:
      - ${PORT}:80
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    labels:
      ho.ctf.cyrhades: "1"
